all:
  children:
    openclaw_vm:
      vars:
        ansible_connection: ssh
        ansible_shell_type: powershell
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      hosts:
        vm-ymms-openclaw-01:
        vm-ymms-openclaw-02:
